Features/test generating
NovaLite-doo/grupna-praksa-oktobar-2024 pull request #17
Opened 2024-10-17 13:02 UTC by Batranovic

2024-10-17 13:14 UTC, OgnjenGligoric commented on Konteh/Konteh.Infrastructure/Repositories/ExamRepository.cs
> +        {
Consider removing this repository if it's currently not adding any additional functionality or value to the project.

2024-10-17 13:19 UTC, OgnjenGligoric commented on Konteh/Konteh.Tests/GenerateExamTests.cs
> +            var command = new GenerateExam.Command { QuestionPerCategpry = 2 };
Typo in ```QuestionPerCategory```.

2024-10-17 13:34 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Features/Exams/GenerateExam.cs
> +            public List<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();
We shouldn't expose our domain models through the API, please create a DTO.

2024-10-17 13:34 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Features/Exams/GenerateExam.cs
> +                foreach (QuestionCategory category in Categories)
please use implicit types

2024-10-17 13:35 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Features/Exams/GenerateExam.cs
> +
:)

2024-10-17 13:35 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Konteh - Backup.BackOfficeApi.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
what is this?

2024-10-17 13:36 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Utils/IRandomGenerator.cs
> +﻿namespace Konteh.BackOfficeApi.Utils
Lets avoid folder names like "utils", "helpers", etc. It's far to generic and could contain anything. I know naming is hard, but it's important.

2024-10-17 13:36 UTC, laslorajda commented on Konteh/Konteh.Infrastructure/Migrations/20241016125812_initialMig.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
?

2024-10-17 13:38 UTC, laslorajda commented on Konteh/Konteh.Tests/GenerateExamTests.Handle_ShouldCreateExam_WithTwoQuestionsPerCategory.verified.txt
> +        Category: General
I know it's boring, but can we make our test data a bit more realistic? For example questions without text/answers don't make much sense.

2024-10-17 13:39 UTC, laslorajda commented on Konteh/Konteh.Tests/GenerateExamTests.Handle_ShouldCreateExam_WithTwoQuestionsPerCategory_MultipleRuns.verified.txt
> +﻿{
only one test uses verifier yet there are 2 verified files? something is off

2024-10-17 13:40 UTC, laslorajda commented on Konteh/Konteh.Tests/GenerateExamTests.cs
> +            //Arrange
Only add comments if they contribute something. Most people should be familiar with AAA testing.

2024-10-17 13:41 UTC, laslorajda requested changes
Mostly fine, some fine tuning is needed though

2024-10-18 07:50 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Features/Exams/GenerateExam.cs
> +                            IsCorrect = a.IsCorrect
So I just noticed that this is in BackOfficeApi, but it was supposed to be in FrontOfficeApi(since tests will be generated when a candidate requests it). With that said, I don't think we should return to the front office app which answers are correct!

2024-10-18 07:50 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Konteh - Backup.BackOfficeApi.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
This file is still here?

2024-10-18 07:51 UTC, laslorajda commented on Konteh/Konteh.Infrastructure/Migrations/20241014122257_InitialMigration.cs
Why delete the initial migration? 😄

2024-10-18 08:27 UTC, laslorajda approved these changes

2024-10-18 08:27 UTC, merged